In [3]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/RO361326/scikit_learn_data/mldata/knndata.csv')

In [4]:
df.head()

Age   year   nodes   Survival 
0    30     64       1          1
1    30     62       3          1
2    30     65       0          1
3    31     59       2          1
4    31     65       4          1

In [39]:
df.columns
y = df['Survival ']
X = df.drop(['Survival '],axis = 1)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

clf = KNeighborsClassifier()

In [43]:
x_tr = (np.array(x_train))
y_tr = (np.array(y_train))
x_ts = (np.array(x_test))
y_ts = (np.array(y_test))

In [44]:
clf.fit(x_tr,y_tr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [46]:
clf.score(x_ts,y_ts)

0.7741935483870968

In [47]:
p = clf.predict(x_ts)
p

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1], dtype=int64)

In [48]:
y_ts

array([2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2], dtype=int64)

In [49]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_ts,p)
mat

array([[43,  5],
       [ 9,  5]], dtype=int64)